/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ComponentsIndexRouteImport } from './routes/components.index'
import { Route as ISplatRouteImport } from './routes/i.$'
import { Route as DashboardNewRouteImport } from './routes/dashboard.new'
import { Route as ApiUploadAvatarRouteImport } from './routes/api/upload-avatar'
import { Route as ComponentsNamespaceNameRouteImport } from './routes/components.$namespace.$name'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ISplatRoute = ISplatRouteImport.update({
  id: '/i/$',
  path: '/i/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiUploadAvatarRoute = ApiUploadAvatarRouteImport.update({
  id: '/api/upload-avatar',
  path: '/api/upload-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsNamespaceNameRoute = ComponentsNamespaceNameRouteImport.update({
  id: '/components/$namespace/$name',
  path: '/components/$namespace/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/api/upload-avatar': typeof ApiUploadAvatarRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/i/$': typeof ISplatRoute
  '/components/': typeof ComponentsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/components/$namespace/$name': typeof ComponentsNamespaceNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/api/upload-avatar': typeof ApiUploadAvatarRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/i/$': typeof ISplatRoute
  '/components': typeof ComponentsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/components/$namespace/$name': typeof ComponentsNamespaceNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/api/upload-avatar': typeof ApiUploadAvatarRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/i/$': typeof ISplatRoute
  '/components/': typeof ComponentsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/components/$namespace/$name': typeof ComponentsNamespaceNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/dashboard'
    | '/settings'
    | '/signin'
    | '/api/upload-avatar'
    | '/dashboard/new'
    | '/i/$'
    | '/components/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/components/$namespace/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/settings'
    | '/signin'
    | '/api/upload-avatar'
    | '/dashboard/new'
    | '/i/$'
    | '/components'
    | '/dashboard'
    | '/api/auth/$'
    | '/components/$namespace/$name'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/dashboard'
    | '/settings'
    | '/signin'
    | '/api/upload-avatar'
    | '/dashboard/new'
    | '/i/$'
    | '/components/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/components/$namespace/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  ApiUploadAvatarRoute: typeof ApiUploadAvatarRoute
  ISplatRoute: typeof ISplatRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ComponentsNamespaceNameRoute: typeof ComponentsNamespaceNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$': {
      id: '/i/$'
      path: '/i/$'
      fullPath: '/i/$'
      preLoaderRoute: typeof ISplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/upload-avatar': {
      id: '/api/upload-avatar'
      path: '/api/upload-avatar'
      fullPath: '/api/upload-avatar'
      preLoaderRoute: typeof ApiUploadAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$namespace/$name': {
      id: '/components/$namespace/$name'
      path: '/components/$namespace/$name'
      fullPath: '/components/$namespace/$name'
      preLoaderRoute: typeof ComponentsNamespaceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardNewRoute: DashboardNewRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  ApiUploadAvatarRoute: ApiUploadAvatarRoute,
  ISplatRoute: ISplatRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ComponentsNamespaceNameRoute: ComponentsNamespaceNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
