/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SandboxTestRouteImport } from './routes/sandbox-test'
import { Route as PublishingPolicyRouteImport } from './routes/publishing-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ComponentsIndexRouteImport } from './routes/components.index'
import { Route as ReviewIdRouteImport } from './routes/review.$id'
import { Route as RSplatRouteImport } from './routes/r.$'
import { Route as ISplatRouteImport } from './routes/i.$'
import { Route as DashboardNewRouteImport } from './routes/dashboard.new'
import { Route as DashboardComponentsRouteImport } from './routes/dashboard.components'
import { Route as ApiUploadAvatarRouteImport } from './routes/api/upload-avatar'
import { Route as DashboardEditNameRouteImport } from './routes/dashboard.edit.$name'
import { Route as ComponentsNamespaceNameRouteImport } from './routes/components.$namespace.$name'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxTestRoute = SandboxTestRouteImport.update({
  id: '/sandbox-test',
  path: '/sandbox-test',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishingPolicyRoute = PublishingPolicyRouteImport.update({
  id: '/publishing-policy',
  path: '/publishing-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIdRoute = ReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RSplatRoute = RSplatRouteImport.update({
  id: '/r/$',
  path: '/r/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ISplatRoute = ISplatRouteImport.update({
  id: '/i/$',
  path: '/i/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComponentsRoute = DashboardComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiUploadAvatarRoute = ApiUploadAvatarRouteImport.update({
  id: '/api/upload-avatar',
  path: '/api/upload-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEditNameRoute = DashboardEditNameRouteImport.update({
  id: '/edit/$name',
  path: '/edit/$name',
  getParentRoute: () => DashboardRoute,
} as any)
const ComponentsNamespaceNameRoute = ComponentsNamespaceNameRouteImport.update({
  id: '/components/$namespace/$name',
  path: '/components/$namespace/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/publishing-policy': typeof PublishingPolicyRoute
  '/sandbox-test': typeof SandboxTestRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/api/upload-avatar': typeof ApiUploadAvatarRoute
  '/dashboard/components': typeof DashboardComponentsRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/i/$': typeof ISplatRoute
  '/r/$': typeof RSplatRoute
  '/review/$id': typeof ReviewIdRoute
  '/components/': typeof ComponentsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/components/$namespace/$name': typeof ComponentsNamespaceNameRoute
  '/dashboard/edit/$name': typeof DashboardEditNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/privacy': typeof PrivacyRoute
  '/publishing-policy': typeof PublishingPolicyRoute
  '/sandbox-test': typeof SandboxTestRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/api/upload-avatar': typeof ApiUploadAvatarRoute
  '/dashboard/components': typeof DashboardComponentsRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/i/$': typeof ISplatRoute
  '/r/$': typeof RSplatRoute
  '/review/$id': typeof ReviewIdRoute
  '/components': typeof ComponentsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/review': typeof ReviewIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/components/$namespace/$name': typeof ComponentsNamespaceNameRoute
  '/dashboard/edit/$name': typeof DashboardEditNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/publishing-policy': typeof PublishingPolicyRoute
  '/sandbox-test': typeof SandboxTestRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/api/upload-avatar': typeof ApiUploadAvatarRoute
  '/dashboard/components': typeof DashboardComponentsRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/i/$': typeof ISplatRoute
  '/r/$': typeof RSplatRoute
  '/review/$id': typeof ReviewIdRoute
  '/components/': typeof ComponentsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/components/$namespace/$name': typeof ComponentsNamespaceNameRoute
  '/dashboard/edit/$name': typeof DashboardEditNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/dashboard'
    | '/privacy'
    | '/publishing-policy'
    | '/sandbox-test'
    | '/settings'
    | '/signin'
    | '/terms'
    | '/api/upload-avatar'
    | '/dashboard/components'
    | '/dashboard/new'
    | '/i/$'
    | '/r/$'
    | '/review/$id'
    | '/components/'
    | '/dashboard/'
    | '/review/'
    | '/api/auth/$'
    | '/components/$namespace/$name'
    | '/dashboard/edit/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/privacy'
    | '/publishing-policy'
    | '/sandbox-test'
    | '/settings'
    | '/signin'
    | '/terms'
    | '/api/upload-avatar'
    | '/dashboard/components'
    | '/dashboard/new'
    | '/i/$'
    | '/r/$'
    | '/review/$id'
    | '/components'
    | '/dashboard'
    | '/review'
    | '/api/auth/$'
    | '/components/$namespace/$name'
    | '/dashboard/edit/$name'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/dashboard'
    | '/privacy'
    | '/publishing-policy'
    | '/sandbox-test'
    | '/settings'
    | '/signin'
    | '/terms'
    | '/api/upload-avatar'
    | '/dashboard/components'
    | '/dashboard/new'
    | '/i/$'
    | '/r/$'
    | '/review/$id'
    | '/components/'
    | '/dashboard/'
    | '/review/'
    | '/api/auth/$'
    | '/components/$namespace/$name'
    | '/dashboard/edit/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  PublishingPolicyRoute: typeof PublishingPolicyRoute
  SandboxTestRoute: typeof SandboxTestRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  TermsRoute: typeof TermsRoute
  ApiUploadAvatarRoute: typeof ApiUploadAvatarRoute
  ISplatRoute: typeof ISplatRoute
  RSplatRoute: typeof RSplatRoute
  ReviewIdRoute: typeof ReviewIdRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ComponentsNamespaceNameRoute: typeof ComponentsNamespaceNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox-test': {
      id: '/sandbox-test'
      path: '/sandbox-test'
      fullPath: '/sandbox-test'
      preLoaderRoute: typeof SandboxTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishing-policy': {
      id: '/publishing-policy'
      path: '/publishing-policy'
      fullPath: '/publishing-policy'
      preLoaderRoute: typeof PublishingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$id': {
      id: '/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof ReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$': {
      id: '/r/$'
      path: '/r/$'
      fullPath: '/r/$'
      preLoaderRoute: typeof RSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$': {
      id: '/i/$'
      path: '/i/$'
      fullPath: '/i/$'
      preLoaderRoute: typeof ISplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/components': {
      id: '/dashboard/components'
      path: '/components'
      fullPath: '/dashboard/components'
      preLoaderRoute: typeof DashboardComponentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/upload-avatar': {
      id: '/api/upload-avatar'
      path: '/api/upload-avatar'
      fullPath: '/api/upload-avatar'
      preLoaderRoute: typeof ApiUploadAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/edit/$name': {
      id: '/dashboard/edit/$name'
      path: '/edit/$name'
      fullPath: '/dashboard/edit/$name'
      preLoaderRoute: typeof DashboardEditNameRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/components/$namespace/$name': {
      id: '/components/$namespace/$name'
      path: '/components/$namespace/$name'
      fullPath: '/components/$namespace/$name'
      preLoaderRoute: typeof ComponentsNamespaceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardComponentsRoute: typeof DashboardComponentsRoute
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEditNameRoute: typeof DashboardEditNameRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardComponentsRoute: DashboardComponentsRoute,
  DashboardNewRoute: DashboardNewRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEditNameRoute: DashboardEditNameRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  PublishingPolicyRoute: PublishingPolicyRoute,
  SandboxTestRoute: SandboxTestRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  TermsRoute: TermsRoute,
  ApiUploadAvatarRoute: ApiUploadAvatarRoute,
  ISplatRoute: ISplatRoute,
  RSplatRoute: RSplatRoute,
  ReviewIdRoute: ReviewIdRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ComponentsNamespaceNameRoute: ComponentsNamespaceNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
