// AUTO-GENERATED from Shiki bundled themes. Do not edit by hand.
// Regenerate: node scripts/gen-theme-palettes.mjs

export interface ThemePalette {
  id: string;
  name: string;
  type: "light" | "dark";
  bg: string;
  fg: string;
  keyword: string;
  string: string;
  func: string;
  comment: string;
  variable: string;
  number: string;
}

export const THEME_PALETTES: ThemePalette[] = [
  {
    "id": "andromeeda",
    "name": "Andromeeda",
    "type": "dark",
    "bg": "#23262E",
    "fg": "#D5CED9",
    "keyword": "#f39c12",
    "string": "#D5CED9",
    "func": "#FFE66D",
    "comment": "#A0A1A7cc",
    "variable": "#00e8c6",
    "number": "#f39c12"
  },
  {
    "id": "aurora-x",
    "name": "Aurora X",
    "type": "dark",
    "bg": "#07090F",
    "fg": "#c9d1d9",
    "keyword": "#C792EA",
    "string": "#EEFFFF",
    "func": "#82AAFF",
    "comment": "#546E7A",
    "variable": "#EEFFFF",
    "number": "#F78C6C"
  },
  {
    "id": "ayu-dark",
    "name": "Ayu Dark",
    "type": "dark",
    "bg": "#10141c",
    "fg": "#bfbdb6",
    "keyword": "#ff8f40",
    "string": "#aad94c",
    "func": "#ffb454",
    "comment": "#5a6673",
    "variable": "#bfbdb6",
    "number": "#d2a6ff"
  },
  {
    "id": "ayu-light",
    "name": "Ayu Light",
    "type": "light",
    "bg": "#fcfcfc",
    "fg": "#5c6166",
    "keyword": "#fa8532",
    "string": "#86b300",
    "func": "#eba400",
    "comment": "#adaeb1",
    "variable": "#5c6166",
    "number": "#a37acc"
  },
  {
    "id": "ayu-mirage",
    "name": "Ayu Mirage",
    "type": "dark",
    "bg": "#242936",
    "fg": "#cccac2",
    "keyword": "#ffa659",
    "string": "#d5ff80",
    "func": "#ffcd66",
    "comment": "#6e7c8f",
    "variable": "#cccac2",
    "number": "#dfbfff"
  },
  {
    "id": "catppuccin-frappe",
    "name": "Catppuccin Frappé",
    "type": "dark",
    "bg": "#303446",
    "fg": "#c6d0f5",
    "keyword": "#ef9f76",
    "string": "#a6d189",
    "func": "#8caaee",
    "comment": "#949cbb",
    "variable": "#c6d0f5",
    "number": "#ef9f76"
  },
  {
    "id": "catppuccin-latte",
    "name": "Catppuccin Latte",
    "type": "light",
    "bg": "#eff1f5",
    "fg": "#4c4f69",
    "keyword": "#fe640b",
    "string": "#40a02b",
    "func": "#1e66f5",
    "comment": "#7c7f93",
    "variable": "#4c4f69",
    "number": "#fe640b"
  },
  {
    "id": "catppuccin-macchiato",
    "name": "Catppuccin Macchiato",
    "type": "dark",
    "bg": "#24273a",
    "fg": "#cad3f5",
    "keyword": "#f5a97f",
    "string": "#a6da95",
    "func": "#8aadf4",
    "comment": "#939ab7",
    "variable": "#cad3f5",
    "number": "#f5a97f"
  },
  {
    "id": "catppuccin-mocha",
    "name": "Catppuccin Mocha",
    "type": "dark",
    "bg": "#1e1e2e",
    "fg": "#cdd6f4",
    "keyword": "#fab387",
    "string": "#a6e3a1",
    "func": "#89b4fa",
    "comment": "#9399b2",
    "variable": "#cdd6f4",
    "number": "#fab387"
  },
  {
    "id": "dark-plus",
    "name": "Dark Plus",
    "type": "dark",
    "bg": "#1E1E1E",
    "fg": "#D4D4D4",
    "keyword": "#b5cea8",
    "string": "#D4D4D4",
    "func": "#569cd6",
    "comment": "#6A9955",
    "variable": "#D4D4D4",
    "number": "#b5cea8"
  },
  {
    "id": "dracula",
    "name": "Dracula Theme",
    "type": "dark",
    "bg": "#282A36",
    "fg": "#F8F8F2",
    "keyword": "#BD93F9",
    "string": "#FF79C6",
    "func": "#50FA7B",
    "comment": "#6272A4",
    "variable": "#BD93F9",
    "number": "#BD93F9"
  },
  {
    "id": "dracula-soft",
    "name": "Dracula Theme Soft",
    "type": "dark",
    "bg": "#282A36",
    "fg": "#f6f6f4",
    "keyword": "#bf9eee",
    "string": "#f286c4",
    "func": "#62e884",
    "comment": "#7b7f8b",
    "variable": "#bf9eee",
    "number": "#bf9eee"
  },
  {
    "id": "everforest-dark",
    "name": "Everforest Dark",
    "type": "dark",
    "bg": "#2d353b",
    "fg": "#d3c6aa",
    "keyword": "#e67e80",
    "string": "#dbbc7f",
    "func": "#a7c080",
    "comment": "#859289",
    "variable": "#a7c080",
    "number": "#d699b6"
  },
  {
    "id": "everforest-light",
    "name": "Everforest Light",
    "type": "light",
    "bg": "#fdf6e3",
    "fg": "#5c6a72",
    "keyword": "#f85552",
    "string": "#dfa000",
    "func": "#8da101",
    "comment": "#939f91",
    "variable": "#8da101",
    "number": "#df69ba"
  },
  {
    "id": "github-dark",
    "name": "GitHub Dark",
    "type": "dark",
    "bg": "#24292e",
    "fg": "#e1e4e8",
    "keyword": "#f97583",
    "string": "#6a737d",
    "func": "#e1e4e8",
    "comment": "#6a737d",
    "variable": "#79b8ff",
    "number": "#79b8ff"
  },
  {
    "id": "github-dark-default",
    "name": "GitHub Dark Default",
    "type": "dark",
    "bg": "#0d1117",
    "fg": "#e6edf3",
    "keyword": "#ff7b72",
    "string": "#8b949e",
    "func": "#d2a8ff",
    "comment": "#8b949e",
    "variable": "#79c0ff",
    "number": "#ff7b72"
  },
  {
    "id": "github-dark-dimmed",
    "name": "GitHub Dark Dimmed",
    "type": "dark",
    "bg": "#22272e",
    "fg": "#adbac7",
    "keyword": "#f47067",
    "string": "#768390",
    "func": "#dcbdfb",
    "comment": "#768390",
    "variable": "#6cb6ff",
    "number": "#f47067"
  },
  {
    "id": "github-dark-high-contrast",
    "name": "GitHub Dark High Contrast",
    "type": "dark",
    "bg": "#0a0c10",
    "fg": "#f0f3f6",
    "keyword": "#ff9492",
    "string": "#bdc4cc",
    "func": "#dbb7ff",
    "comment": "#bdc4cc",
    "variable": "#91cbff",
    "number": "#ff9492"
  },
  {
    "id": "github-light",
    "name": "GitHub Light",
    "type": "light",
    "bg": "#fff",
    "fg": "#24292e",
    "keyword": "#d73a49",
    "string": "#6a737d",
    "func": "#24292e",
    "comment": "#6a737d",
    "variable": "#005cc5",
    "number": "#005cc5"
  },
  {
    "id": "github-light-default",
    "name": "GitHub Light Default",
    "type": "light",
    "bg": "#ffffff",
    "fg": "#1f2328",
    "keyword": "#cf222e",
    "string": "#6e7781",
    "func": "#8250df",
    "comment": "#6e7781",
    "variable": "#0550ae",
    "number": "#cf222e"
  },
  {
    "id": "github-light-high-contrast",
    "name": "GitHub Light High Contrast",
    "type": "light",
    "bg": "#ffffff",
    "fg": "#0e1116",
    "keyword": "#a0111f",
    "string": "#66707b",
    "func": "#622cbc",
    "comment": "#66707b",
    "variable": "#023b95",
    "number": "#a0111f"
  },
  {
    "id": "gruvbox-dark-hard",
    "name": "Gruvbox Dark Hard",
    "type": "dark",
    "bg": "#1d2021",
    "fg": "#ebdbb2",
    "keyword": "#fb4934",
    "string": "#b8bb26",
    "func": "#fabd2f",
    "comment": "#928374",
    "variable": "#d3869b",
    "number": "#d3869b"
  },
  {
    "id": "gruvbox-dark-medium",
    "name": "Gruvbox Dark Medium",
    "type": "dark",
    "bg": "#282828",
    "fg": "#ebdbb2",
    "keyword": "#fb4934",
    "string": "#b8bb26",
    "func": "#fabd2f",
    "comment": "#928374",
    "variable": "#d3869b",
    "number": "#d3869b"
  },
  {
    "id": "gruvbox-dark-soft",
    "name": "Gruvbox Dark Soft",
    "type": "dark",
    "bg": "#32302f",
    "fg": "#ebdbb2",
    "keyword": "#fb4934",
    "string": "#b8bb26",
    "func": "#fabd2f",
    "comment": "#928374",
    "variable": "#d3869b",
    "number": "#d3869b"
  },
  {
    "id": "gruvbox-light-hard",
    "name": "Gruvbox Light Hard",
    "type": "light",
    "bg": "#f9f5d7",
    "fg": "#3c3836",
    "keyword": "#9d0006",
    "string": "#79740e",
    "func": "#b57614",
    "comment": "#928374",
    "variable": "#8f3f71",
    "number": "#8f3f71"
  },
  {
    "id": "gruvbox-light-medium",
    "name": "Gruvbox Light Medium",
    "type": "light",
    "bg": "#fbf1c7",
    "fg": "#3c3836",
    "keyword": "#9d0006",
    "string": "#79740e",
    "func": "#b57614",
    "comment": "#928374",
    "variable": "#8f3f71",
    "number": "#8f3f71"
  },
  {
    "id": "gruvbox-light-soft",
    "name": "Gruvbox Light Soft",
    "type": "light",
    "bg": "#f2e5bc",
    "fg": "#3c3836",
    "keyword": "#9d0006",
    "string": "#79740e",
    "func": "#b57614",
    "comment": "#928374",
    "variable": "#8f3f71",
    "number": "#8f3f71"
  },
  {
    "id": "horizon",
    "name": "Horizon",
    "type": "dark",
    "bg": "#1C1E26",
    "fg": "#c9d1d9",
    "keyword": "#B877DBE6",
    "string": "#FAB795E6",
    "func": "#25B0BCE6",
    "comment": "#BBBBBB4D",
    "variable": "#E95678E6",
    "number": "#F09483E6"
  },
  {
    "id": "horizon-bright",
    "name": "Horizon Bright",
    "type": "light",
    "bg": "#FDF0ED",
    "fg": "#c9d1d9",
    "keyword": "#8A31B9",
    "string": "#F6661E",
    "func": "#1D8991",
    "comment": "#33333380",
    "variable": "#DA103F",
    "number": "#DC3318"
  },
  {
    "id": "houston",
    "name": "Houston",
    "type": "dark",
    "bg": "#17191e",
    "fg": "#eef0f9",
    "keyword": "#ffd493",
    "string": "#ffd493",
    "func": "#00daef",
    "comment": "#545864",
    "variable": "#54b9ff",
    "number": "#ffd493"
  },
  {
    "id": "kanagawa-dragon",
    "name": "Kanagawa Dragon",
    "type": "dark",
    "bg": "#181616",
    "fg": "#C5C9C5",
    "keyword": "#8992A7",
    "string": "#C5C9C5",
    "func": "#8BA4B0",
    "comment": "#737C73",
    "variable": "#C5C9C5",
    "number": "#B6927B"
  },
  {
    "id": "kanagawa-lotus",
    "name": "Kanagawa Lotus",
    "type": "light",
    "bg": "#F2ECBC",
    "fg": "#545464",
    "keyword": "#624C83",
    "string": "#545464",
    "func": "#4D699B",
    "comment": "#716E61",
    "variable": "#545464",
    "number": "#CC6D00"
  },
  {
    "id": "kanagawa-wave",
    "name": "Kanagawa Wave",
    "type": "dark",
    "bg": "#1F1F28",
    "fg": "#DCD7BA",
    "keyword": "#957FB8",
    "string": "#DCD7BA",
    "func": "#7E9CD8",
    "comment": "#727169",
    "variable": "#DCD7BA",
    "number": "#FFA066"
  },
  {
    "id": "laserwave",
    "name": "LaserWave",
    "type": "dark",
    "bg": "#27212e",
    "fg": "#ffffff",
    "keyword": "#40b4c4",
    "string": "#b4dce7",
    "func": "#EB64B9",
    "comment": "#91889b",
    "variable": "#40b4c4",
    "number": "#b381c5"
  },
  {
    "id": "light-plus",
    "name": "Light Plus",
    "type": "light",
    "bg": "#FFFFFF",
    "fg": "#000000",
    "keyword": "#098658",
    "string": "#000000ff",
    "func": "#0000ff",
    "comment": "#008000",
    "variable": "#000000ff",
    "number": "#098658"
  },
  {
    "id": "material-theme",
    "name": "Material Theme",
    "type": "dark",
    "bg": "#263238",
    "fg": "#EEFFFF",
    "keyword": "#F78C6C",
    "string": "#C3E88D",
    "func": "#EEFFFF",
    "comment": "#546E7A",
    "variable": "#EEFFFF",
    "number": "#F78C6C"
  },
  {
    "id": "material-theme-darker",
    "name": "Material Theme Darker",
    "type": "dark",
    "bg": "#212121",
    "fg": "#EEFFFF",
    "keyword": "#F78C6C",
    "string": "#C3E88D",
    "func": "#EEFFFF",
    "comment": "#545454",
    "variable": "#EEFFFF",
    "number": "#F78C6C"
  },
  {
    "id": "material-theme-lighter",
    "name": "Material Theme Lighter",
    "type": "light",
    "bg": "#FAFAFA",
    "fg": "#90A4AE",
    "keyword": "#F76D47",
    "string": "#91B859",
    "func": "#90A4AE",
    "comment": "#90A4AE",
    "variable": "#90A4AE",
    "number": "#F76D47"
  },
  {
    "id": "material-theme-ocean",
    "name": "Material Theme Ocean",
    "type": "dark",
    "bg": "#0F111A",
    "fg": "#babed8",
    "keyword": "#F78C6C",
    "string": "#C3E88D",
    "func": "#babed8",
    "comment": "#464B5D",
    "variable": "#babed8",
    "number": "#F78C6C"
  },
  {
    "id": "material-theme-palenight",
    "name": "Material Theme Palenight",
    "type": "dark",
    "bg": "#292D3E",
    "fg": "#babed8",
    "keyword": "#F78C6C",
    "string": "#C3E88D",
    "func": "#babed8",
    "comment": "#676E95",
    "variable": "#babed8",
    "number": "#F78C6C"
  },
  {
    "id": "min-dark",
    "name": "Min Dark",
    "type": "dark",
    "bg": "#1f1f1f",
    "fg": "#c9d1d9",
    "keyword": "#b392f0",
    "string": "#9db1c5",
    "func": "#f97583",
    "comment": "#6b737c",
    "variable": "#79b8ff",
    "number": "#f8f8f8"
  },
  {
    "id": "min-light",
    "name": "Min Light",
    "type": "light",
    "bg": "#ffffff",
    "fg": "#212121",
    "keyword": "#24292eff",
    "string": "#2b5581",
    "func": "#D32F2F",
    "comment": "#c2c3c5",
    "variable": "#1976D2",
    "number": "#1976D2"
  },
  {
    "id": "monokai",
    "name": "Monokai",
    "type": "dark",
    "bg": "#272822",
    "fg": "#f8f8f2",
    "keyword": "#F92672",
    "string": "#F8F8F2",
    "func": "#A6E22E",
    "comment": "#88846f",
    "variable": "#F8F8F2",
    "number": "#AE81FF"
  },
  {
    "id": "night-owl",
    "name": "Night Owl",
    "type": "dark",
    "bg": "#011627",
    "fg": "#d6deeb",
    "keyword": "#5ca7e4",
    "string": "#ecc48d",
    "func": "#c792ea",
    "comment": "#637777",
    "variable": "#ecc48d",
    "number": "#F78C6C"
  },
  {
    "id": "night-owl-light",
    "name": "Night Owl Light",
    "type": "light",
    "bg": "#FBFBFB",
    "fg": "#403f53",
    "keyword": "#5ca7e4",
    "string": "#4876d6",
    "func": "#994cc3",
    "comment": "#989fb1",
    "variable": "#c96765",
    "number": "#aa0982"
  },
  {
    "id": "nord",
    "name": "Nord",
    "type": "dark",
    "bg": "#2e3440",
    "fg": "#d8dee9",
    "keyword": "#81A1C1",
    "string": "#A3BE8C",
    "func": "#88C0D0",
    "comment": "#616E88",
    "variable": "#81A1C1",
    "number": "#B48EAD"
  },
  {
    "id": "one-dark-pro",
    "name": "One Dark Pro",
    "type": "dark",
    "bg": "#282c34",
    "fg": "#abb2bf",
    "keyword": "#c678dd",
    "string": "#98c379",
    "func": "#61afef",
    "comment": "#5c6370",
    "variable": "#c678dd",
    "number": "#d19a66"
  },
  {
    "id": "one-light",
    "name": "One Light",
    "type": "light",
    "bg": "#FAFAFA",
    "fg": "#383A42",
    "keyword": "#A626A4",
    "string": "#50A14F",
    "func": "#4078F2",
    "comment": "#A0A1A7",
    "variable": "#986801",
    "number": "#986801"
  },
  {
    "id": "plastic",
    "name": "Plastic",
    "type": "dark",
    "bg": "#21252B",
    "fg": "#A9B2C3",
    "keyword": "#E06C75",
    "string": "#98C379",
    "func": "#B57EDC",
    "comment": "#5F6672",
    "variable": "#E06C75",
    "number": "#56B6C2"
  },
  {
    "id": "poimandres",
    "name": "Poimandres",
    "type": "dark",
    "bg": "#1b1e28",
    "fg": "#a6accd",
    "keyword": "#5DE4c7c0",
    "string": "#ADD7FF",
    "func": "#ADD7FF",
    "comment": "#767c9dB0",
    "variable": "#ADD7FF",
    "number": "#5DE4c7"
  },
  {
    "id": "red",
    "name": "Red",
    "type": "dark",
    "bg": "#390000",
    "fg": "#F8F8F8",
    "keyword": "#f12727ff",
    "string": "#F8F8F8",
    "func": "#ffb454ff",
    "comment": "#e7c0c0ff",
    "variable": "#F8F8F8",
    "number": "#994646ff"
  },
  {
    "id": "rose-pine",
    "name": "Rosé Pine",
    "type": "dark",
    "bg": "#191724",
    "fg": "#e0def4",
    "keyword": "#31748f",
    "string": "#f6c177",
    "func": "#eb6f92",
    "comment": "#6e6a86",
    "variable": "#31748f",
    "number": "#ebbcba"
  },
  {
    "id": "rose-pine-dawn",
    "name": "Rosé Pine Dawn",
    "type": "light",
    "bg": "#faf4ed",
    "fg": "#575279",
    "keyword": "#286983",
    "string": "#ea9d34",
    "func": "#b4637a",
    "comment": "#9893a5",
    "variable": "#286983",
    "number": "#d7827e"
  },
  {
    "id": "rose-pine-moon",
    "name": "Rosé Pine Moon",
    "type": "dark",
    "bg": "#232136",
    "fg": "#e0def4",
    "keyword": "#3e8fb0",
    "string": "#f6c177",
    "func": "#eb6f92",
    "comment": "#6e6a86",
    "variable": "#3e8fb0",
    "number": "#ea9a97"
  },
  {
    "id": "slack-dark",
    "name": "Slack Dark",
    "type": "dark",
    "bg": "#222222",
    "fg": "#E6E6E6",
    "keyword": "#569cd6",
    "string": "#ce9178",
    "func": "#DCDCAA",
    "comment": "#6A9955",
    "variable": "#9cdcfe",
    "number": "#b5cea8"
  },
  {
    "id": "slack-ochin",
    "name": "Slack Ochin",
    "type": "light",
    "bg": "#FFF",
    "fg": "#000",
    "keyword": "#7b30d0",
    "string": "#110000",
    "func": "#7eb233",
    "comment": "#357b42",
    "variable": "#2f86d2",
    "number": "#174781"
  },
  {
    "id": "snazzy-light",
    "name": "Snazzy Light",
    "type": "light",
    "bg": "#FAFBFC",
    "fg": "#565869",
    "keyword": "#F767BB",
    "string": "#11658F",
    "func": "#09A1ED",
    "comment": "#ADB1C2",
    "variable": "#2DAE58",
    "number": "#FF5C57"
  },
  {
    "id": "solarized-dark",
    "name": "Solarized Dark",
    "type": "dark",
    "bg": "#002B36",
    "fg": "#839496",
    "keyword": "#859900",
    "string": "#839496",
    "func": "#268BD2",
    "comment": "#586E75",
    "variable": "#839496",
    "number": "#D33682"
  },
  {
    "id": "solarized-light",
    "name": "Solarized Light",
    "type": "light",
    "bg": "#FDF6E3",
    "fg": "#657B83",
    "keyword": "#859900",
    "string": "#657B83",
    "func": "#268BD2",
    "comment": "#93A1A1",
    "variable": "#657B83",
    "number": "#D33682"
  },
  {
    "id": "synthwave-84",
    "name": "Synthwave '84",
    "type": "dark",
    "bg": "#262335",
    "fg": "#c9d1d9",
    "keyword": "#72f1b8",
    "string": "#848bbd",
    "func": "#36f9f6",
    "comment": "#848bbd",
    "variable": "#ff7edb",
    "number": "#f97e72"
  },
  {
    "id": "tokyo-night",
    "name": "Tokyo Night",
    "type": "dark",
    "bg": "#1a1b26",
    "fg": "#a9b1d6",
    "keyword": "#5a638c",
    "string": "#51597d",
    "func": "#0db9d7",
    "comment": "#51597d",
    "variable": "#5a638c",
    "number": "#ff9e64"
  },
  {
    "id": "vesper",
    "name": "Vesper",
    "type": "dark",
    "bg": "#101010",
    "fg": "#FFF",
    "keyword": "#A0A0A0",
    "string": "#FFF",
    "func": "#FFC799",
    "comment": "#8b8b8b94",
    "variable": "#FFF",
    "number": "#FFC799"
  },
  {
    "id": "vitesse-black",
    "name": "Vitesse Black",
    "type": "dark",
    "bg": "#000",
    "fg": "#dbd7cacc",
    "keyword": "#444444",
    "string": "#758575dd",
    "func": "#80a665",
    "comment": "#758575dd",
    "variable": "#c99076",
    "number": "#4C9A91"
  },
  {
    "id": "vitesse-dark",
    "name": "Vitesse Dark",
    "type": "dark",
    "bg": "#121212",
    "fg": "#dbd7caee",
    "keyword": "#666666",
    "string": "#758575dd",
    "func": "#80a665",
    "comment": "#758575dd",
    "variable": "#c99076",
    "number": "#4C9A91"
  },
  {
    "id": "vitesse-light",
    "name": "Vitesse Light",
    "type": "light",
    "bg": "#ffffff",
    "fg": "#393a34",
    "keyword": "#999999",
    "string": "#a0ada0",
    "func": "#59873a",
    "comment": "#a0ada0",
    "variable": "#a65e2b",
    "number": "#2f798a"
  }
];
